# Generated by Django 6.0 on 2026-06-19 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gegenstand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_form_id', models.CharField(max_length=100, unique=True, verbose_name='Zeitstempel/ID von Google')),
                ('titel', models.CharField(max_length=200, verbose_name='Gegenstand')),
                ('beschreibung', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('fundort', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fundort')),
                ('funddatum', models.CharField(blank=True, max_length=100, null=True, verbose_name='Funddatum')),
                ('bild_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Bild-Link (Google Drive)')),
                ('status', models.CharField(choices=[('verfuegbar', 'Verfügbar / Offen'), ('bearbeitung', 'In Bearbeitung / Chat aktiv'), ('ausgehaendigt', 'Ausgehändigt / Abgeschlossen')], default='verfuegbar', max_length=20)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunde_chats', to=settings.AUTH_USER_MODEL)),
                ('gegenstand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='portal.gegenstand')),
            ],
            options={
                'unique_together': {('gegenstand', 'kunde')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nachricht', models.TextField()),
                ('gesendet_am', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('raum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nachrichten', to='portal.chatroom')),
            ],
        ),
        migrations.CreateModel(
            name='UebergabeBericht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uebergabe_datum', models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt der Übergabe')),
                ('bemerkung', models.TextField(blank=True, null=True, verbose_name='Interne Vermerke (z.B. Ausweisnummer)')),
                ('bearbeiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='berichte_erstellt', to=settings.AUTH_USER_MODEL, verbose_name='Mitarbeiter')),
                ('gegenstand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bericht', to='portal.gegenstand')),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='berichte_empfangen', to=settings.AUTH_USER_MODEL, verbose_name='Abholer (Kunde)')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolle', models.CharField(choices=[('kunde', 'Kunde (Suchender)'), ('mitarbeiter', 'Mitarbeiter (Fundbüro-Bearbeiter)')], default='kunde', max_length=20)),
                ('telefonnummer', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
