# Generated by Django 6.0 on 2026-06-21 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='gegenstand',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='kunde',
        ),
        migrations.RemoveField(
            model_name='uebergabebericht',
            name='bearbeiter',
        ),
        migrations.RemoveField(
            model_name='uebergabebericht',
            name='gegenstand',
        ),
        migrations.RemoveField(
            model_name='uebergabebericht',
            name='kunde',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gegenstand',
            name='bild_url',
        ),
        migrations.AlterField(
            model_name='gegenstand',
            name='beschreibung',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gegenstand',
            name='funddatum',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gegenstand',
            name='fundort',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gegenstand',
            name='google_form_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gegenstand',
            name='status',
            field=models.CharField(choices=[('gesucht', 'Gesucht (vom Kunden gemeldet)'), ('gefunden', 'Gefunden (im Bus abgegeben)'), ('rueckgegeben', 'An Eigentümer übergeben')], default='gefunden', max_length=20),
        ),
        migrations.AlterField(
            model_name='gegenstand',
            name='titel',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Bericht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notizen', models.TextField()),
                ('abgeholt_von', models.CharField(blank=True, max_length=200)),
                ('abgeholt_am', models.DateTimeField(blank=True, null=True)),
                ('gegenstand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bericht', to='portal.gegenstand')),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erstellte_berichte', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('gegenstand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='portal.gegenstand')),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunden_chats', to=settings.AUTH_USER_MODEL)),
                ('mitarbeiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mitarbeiter_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GegenstandBild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bild_url', models.URLField(max_length=1000)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('gegenstand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilder', to='portal.gegenstand')),
            ],
            options={
                'verbose_name': 'Gegenstand-Bild',
                'verbose_name_plural': 'Gegenstand-Bilder',
            },
        ),
        migrations.CreateModel(
            name='Nachricht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('gesendet_am', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nachrichten', to='portal.chat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ist_mitarbeiter', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='UebergabeBericht',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
