# Generated by Django 6.0 on 2026-06-25 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_chatroom_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='gegenstand',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='kunde',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='mitarbeiter',
        ),
        migrations.RemoveField(
            model_name='nachricht',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='gegenstandbild',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nachricht',
            options={'ordering': ['zeitstempel']},
        ),
        migrations.RenameField(
            model_name='nachricht',
            old_name='sender',
            new_name='absender',
        ),
        migrations.RenameField(
            model_name='nachricht',
            old_name='gesendet_am',
            new_name='zeitstempel',
        ),
        migrations.RemoveField(
            model_name='gegenstand',
            name='erstellt_am',
        ),
        migrations.RemoveField(
            model_name='gegenstand',
            name='google_form_id',
        ),
        migrations.RemoveField(
            model_name='gegenstandbild',
            name='erstellt_am',
        ),
        migrations.AddField(
            model_name='gegenstandbild',
            name='direkt_bild_url',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nachricht',
            name='gegenstand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='nachrichten', to='portal.gegenstand'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gegenstand',
            name='beschreibung',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gegenstand',
            name='funddatum',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gegenstand',
            name='fundort',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gegenstand',
            name='status',
            field=models.CharField(choices=[('gefunden', 'Gefunden (im Bus abgegeben)'), ('rueckgegeben', 'An Eigentümer übergeben')], default='gefunden', max_length=20),
        ),
        migrations.AlterField(
            model_name='gegenstandbild',
            name='bild_url',
            field=models.URLField(max_length=500),
        ),
        migrations.DeleteModel(
            name='Bericht',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
