# Generated by Django 6.0 on 2026-06-28 15:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_chat_gegenstand_remove_chat_kunde_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gegenstand',
            options={'ordering': ['-funddatum', '-funduhrzeit'], 'verbose_name': 'Fundgegenstand', 'verbose_name_plural': 'Fundgegenstände'},
        ),
        migrations.AlterModelOptions(
            name='gegenstandbild',
            options={'verbose_name': 'Gegenstand Bild', 'verbose_name_plural': 'Gegenstand Bilder'},
        ),
        migrations.RemoveField(
            model_name='gegenstand',
            name='titel',
        ),
        migrations.AddField(
            model_name='gegenstand',
            name='bezeichnung',
            field=models.CharField(default='', max_length=200, verbose_name='Bezeichnung'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gegenstand',
            name='erstellt_am',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='System-Eintragsdatum'),
        ),
        migrations.AddField(
            model_name='gegenstand',
            name='funduhrzeit',
            field=models.TimeField(blank=True, null=True, verbose_name='Funduhrzeit'),
        ),
        migrations.AddField(
            model_name='gegenstand',
            name='unterschriebener_beleg',
            field=models.FileField(blank=True, null=True, upload_to='uebergabebelege/', verbose_name='Gescannter Übergabeschein (PDF/Bild)'),
        ),
        migrations.AlterField(
            model_name='gegenstand',
            name='beschreibung',
            field=models.TextField(verbose_name='Aktueller Verbleib / Beschreibung'),
        ),
        migrations.AlterField(
            model_name='gegenstand',
            name='funddatum',
            field=models.DateField(verbose_name='Funddatum'),
        ),
        migrations.AlterField(
            model_name='gegenstand',
            name='fundort',
            field=models.CharField(max_length=200, verbose_name='Bus-Linie / Fundort'),
        ),
        migrations.AlterField(
            model_name='gegenstand',
            name='status',
            field=models.CharField(choices=[('verfuegbar', 'Verfügbar / Wartet auf Abholung'), ('rueckgegeben', 'An Kunden übergeben / Archiviert'), ('entsorgt', 'Nach Fristablauf entsorgt / Archiviert')], default='verfuegbar', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='gegenstandbild',
            name='bild_url',
            field=models.URLField(max_length=500, verbose_name='Original Bild URL (Google Drive)'),
        ),
        migrations.AlterField(
            model_name='gegenstandbild',
            name='direkt_bild_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Direkt-Lade Bild URL'),
        ),
        migrations.CreateModel(
            name='TicketNachricht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inhalt', models.TextField(verbose_name='Nachrichtentext')),
                ('gesendet_am', models.DateTimeField(auto_now_add=True, verbose_name='Sendezeitpunkt')),
                ('absender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gesendete_nachrichten', to=settings.AUTH_USER_MODEL)),
                ('gegenstand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nachrichten', to='portal.gegenstand')),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunde_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket-Nachricht',
                'verbose_name_plural': 'Ticket-Nachrichten',
                'ordering': ['gesendet_am'],
            },
        ),
        migrations.DeleteModel(
            name='Nachricht',
        ),
    ]
