# Generated by Django 6.0 on 2026-06-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_gegenstand_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gegenstand',
            name='rohe_bild_urls',
            field=models.TextField(blank=True, null=True, verbose_name='Rohe Bild-URLs vom Formular'),
        ),
    ]
